### ISSUE TITLE
Ein paar Fragen zum Aufbau

### ISSUE THREAD

**Issue by TomMajor** [stan23/myPCBs#2]
Hi Marco

- in der Stückliste schreibst du Taster 3301, der hat eine Gesamthöhe von 4,3mm
https://www.reichelt.de/kurzhubtaster-6x6mm-hoehe-4-3mm-12v-vertikal-taster-3301-p27892.html
Im Bild und wenn ich mir das am Gerät anschaue sieht es aber so aus als ob ein höherer Taster verwendet wurde bzw. gebraucht wird.
https://github.com/stan23/myPCBs/blob/master/AskSinAnalyzer/Bilder/Geh%C3%A4use_hinten.jpg
Also 3301 stimmt nicht, oder? Welche Gesamthöhe?

- Auf thingiverse steht M3x18mm Schrauben. Das heisst die Gewindelänge (ohne Kopf) ist 18mm, oder?

- Hättest du eventuell einen Bestelllink auf die verwendete ext. Antenne?

Danke!

**Comment by stan23** [comment]
Hi Tom,
bei den Tastern ist die Höhe nicht so kritisch. Ich hab inzwischen eine größere Sammlung an Tastern und verbaue was mir gerade in die Finger kommt.

4,3 mm Gesamthöhe ist etwas wenig, das stimmt.

Genau das ist die Gewindelänge ohne Kopf, siehe z.B. DIN 7985.

Links reiche ich nach.

**Comment by TomMajor** [comment]
Danke dir, Marco.
ja, der link für die Antenne wäre noch hilfreich.

**Comment by stan23** [comment]
https://github.com/stan23/myPCBs/wiki/AskSinAnalyzer-Hardware#sonstiges
Da sind jetzt 2 Links drin.
Im Prinzip ist es eine beliebige 868 MHz Antenne, mit gewinkeltem SMA male Schraubanschluss.

**Comment by TomMajor** [comment]
Vielen Dank Marco, das hilft.
