### ISSUE TITLE
HB-MOD-UART-USB: some minor bugs

### ISSUE THREAD

**Issue by TomMajor** [stan23/myPCBs#4]
Zunächst mal, habe das Modul aufgebaut und eine VirtualBox VM mit RM aufgesetzt, lief fast  auf Anhieb (das HB-MOD-UART-USB am USB 3.0 Hub mochte die VM nicht, der FT_Prog schon).

Geniales Teil, Danke an Marco (und Jerome für diesen Tipp neulich).
Das macht die AddOn Entwicklung viel angenehmer :)

Issues:
- in der Stückliste ist einmal 100nF zu wenig angegeben
- der in der Reichelt Stückliste angegebene 100u Elko passt überhaupt nicht, m.E. braucht es Case B, nicht Case C

Und eine Warnung an Nachbauer, die SMD BE von Reichelt immer nachmessen, mir haben sie z.B. für den 270 Ohm einen 30k reingelegt :(

Ansonsten, Top-Projekt, Danke.

**Comment by stan23** [comment]
Danke, die Anzahl in der Stückliste habe ich korrigiert.

Dass der Elko zu groß ist habe ich auch festgestellt, da wird das Auflöten etwas schwieriger :)
Leider passt Case C dort vom Footprint nicht wirklich drauf, so dass ich es erstmal so lasse.

**Comment by TomMajor** [comment]
ich musste meinen Case C Elko hochkant legen und dann anlöten.
Warum nicht in der Stückliste auf Case B verweisen?
https://www.reichelt.de/smd-tantal-kondensator-100-f-10-v-taj-3528-100-10-p167015.html

**Comment by stan23** [comment]
Den hatte ich gar nicht gefunden.
Das ist natürlich noch viel besser, vielen Dank!
