### ISSUE TITLE
HB-MOD-UART-USB mit SMA Buchse

### ISSUE THREAD

**Issue by DarkShortie** [stan23/myPCBs#7]
Hallo,

ich versuche gerade der Platine HB-MOD-UART-USB eine SMA Buchse wie bei der HB-MOD-UART hinzuzufügen.
Da ich aber noch nie mit Kicad gearbeitet habe verzweifele ich daran schon den ganzen Abend.

Wäre es möglich so ein Layout zur Verfügung zu stellen?

**Comment by stan23** [comment]
Meinst du so in etwa?

![grafik](https://user-images.githubusercontent.com/4477518/178155540-ac5f0b02-ae30-4da3-bb48-7b0c90c6499d.png)
![grafik](https://user-images.githubusercontent.com/4477518/178155551-8c548847-2abc-4390-b242-c70fdb2765d8.png)

**Comment by DarkShortie** [comment]
Danke. Ja genau so meinte ich das.

**Comment by stan23** [comment]
[HB-MOD-UART-USB_V2.0_Gerber.zip](https://github.com/stan23/myPCBs/files/9079558/HB-MOD-UART-USB_V2.0_Gerber.zip)

Viel Erfolg!

Übrigens, ein HmIP-RF-USB hätte mehr Zukunft:

_Inzwischen unterstützt eQ-3s [HmIP-RFUSB](https://de.elv.com/elv-homematic-ip-arr-bausatz-rf-usb-stick-fuer-alternative-steuerungsplattformen-hmip-rfusb-fuer-smart-home-hausautomation-152306) sowohl [HM- als auch HmIP-Geräte](https://homematic-forum.de/forum/viewtopic.php?f=56&t=70936) und ist eine einfache Alternative._

**Comment by DarkShortie** [comment]
Vielen vielen Dank :)

Der HmIP-RF-USB sieht auch interessant aus, ich bin mir allerdings nicht sicher ob der auch zu meinem Einsatzzweck passt. Ich nutze FHEM, der HB-MOD-UART-USB soll an eine Fritz Box auf der OpenWrt läuft und das ganze soll per ser2net an FHEM weitergeleitet werden. Aktuell ist das ein fliegend verdrahteter Testaufbau, den ich gegen diese Platine tauschen möchte um das ganze etwas robuster zu gestalten.

**Comment by stan23** [comment]
Nein da wird der HmIP-RFUSB wohl nicht funktionieren.
