### ISSUE TITLE
Welche Hardware wird aktuell empfohlen?

### ISSUE THREAD

**Issue by manoloxxl** [stan23/myPCBs#8]
Hi,

Ich möchte endlich den Stick in Betrieb nehmen. Liegt seit Ewigkeit im Keller rum.

Hat jemand einen Tipp für günstige Hardware? Raspis sind ja aktuell nicht so einfach / günstig zu bekommen.

Soll nur die CCU drauf laufen und idealerweise in einem Gehäuse stecken.

Danke!

**Comment by stan23** [comment]
Da kann ich dir leider keinen Tipp geben, bei mir läuft die RaspberryMatic als VM.

Hier findest du mehr Informationen:
https://homematic-forum.de/forum/
